apiVersion: apps/v1
kind: Deployment
metadata:
  name: duios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duios
  template:
    metadata:
      labels:
        app: duios
    spec:
      containers:
      - image: okteto.dev/duios:latest
        name: duios
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d1b2f0a6-4c27-4ef8-a990-d8374e0b4441"
        - name: Vless_Path
          value: "/vldf555"
        - name: Vmess_UUID
          value: "d1b2f0a6-4c27-4ef8-a990-d8374e0b4441"
        - name: Vmess_Path
          value: "/vm6sd66"
        - name: Share_Path
          value: "/v2link"
